#!/usr/bin/python

# Program set wallpaper using feh
# Current Python version when running the program: Python version 3.10.9
# Download file path: $HOME/.konachan/konachan.jpg
# Author: github.com/phamhiep2506

import requests
from bs4 import BeautifulSoup
import os
import sys
import random
from pathlib import Path
import urllib.request
import platform
import subprocess
from datetime import date

KONACHAN_URL = "https://konachan.net"
COLOR_DONE = '\033[92m'
COLOR_ERROR = '\033[91m'
COLOR_WARNING = '\033[93m'
COLOR_END = '\033[0m'

def getID(url):
    try:
        html_doc = requests.get(url).text
    except:
        print(f"{COLOR_ERROR}[Error] Internet connection failed.{COLOR_END}")
        sys.exit(0)

    idArray = []
    data_ul = BeautifulSoup(html_doc, 'html.parser').find('ul', id="post-list-posts")
    data_li = BeautifulSoup(data_ul.prettify(), 'html.parser').find_all('li')

    for x in data_li:
        idArray.append(x.get('id').replace('p', ''))
 
    return random.choice(idArray)

def getIMG():
    prev_day = date.today().day - 1
    month = date.today().month
    year = date.today().year

    id = getID(f"{KONACHAN_URL}/post/popular_by_day?day={prev_day}&month={month}&year={year}")
    html_doc = requests.get(f"{KONACHAN_URL}/post/show/{id}").text
    url_img = BeautifulSoup(html_doc, 'html.parser').find(id="highres").get('href')
    return url_img

def download_progress(block_num, block_size, total_size):
    print(round(block_num * block_size / total_size *100,2), end="\r")

if __name__ == "__main__":
    url_img = getIMG()
    home_dir = Path.home()
    konachan_dir = ".konachan" 
    path_konachan = os.path.join(home_dir, konachan_dir) 

    if not os.path.exists(path_konachan):
        os.mkdir(path_konachan) 

    try:
        print(f"{COLOR_WARNING}[Download] Download image...{COLOR_END}")
        urllib.request.urlretrieve(url_img, f"{path_konachan}/konachan.jpg", download_progress)
    except:
        print(f"{COLOR_ERROR}[Error] Download image failed.{COLOR_END}")

    if platform.system() == "Linux":
        try:
            subprocess.call(["feh", "--bg-max", f"{path_konachan}/konachan.jpg"])
            print(f"{COLOR_DONE}[Done] Set wallpaper successfully.{COLOR_END}")
        except:
            print(f"{COLOR_ERROR}[Error] Set wallpaper failed.{COLOR_END}")
            sys.exit(0)
    else:
        print(f"{COLOR_WARNING}[Warning] The program does not support the OS.{COLOR_END}")
